import { BaseAgent, AgentConfig } from "./base";
import {
  ContextPack,
  Fact,
  StrongSignal,
  HiddenObsession,
  Roast,
  CoworkerQuote,
  StartupParody,
  CareerPrediction,
  InvestigationReport,
  InternetPersonalityScores,
  CookedLevel,
  WildGuess,
  ReportMetadata,
  TokenUsage,
  AgentTrace,
} from "../types";
import { generateId, calculateCost } from "../utils";

const SYSTEM_PROMPT = `You are FinalSynthesis, the master assembler. Your job is to combine all agent outputs into a single comprehensive InvestigationReport.

You will receive:
1. ContextPack — the original profile data
2. Facts — extracted by ProfileAnalyst
3. Strong Signals — detected by SignalDetector
4. Hidden Obsessions — detected by SignalDetector
5. Career Prediction — predicted by CareerPredictor
6. Startup Parody — generated by StartupGenerator
7. Roasts — created by RoastAgent
8. Coworker Quotes — created by RoastAgent
9. Final Verdict — from RoastAgent
10. Governance Violations — if any

## Your Tasks

### 1. Generate Personality Scores (0-100 each)
- **builderScore** — How much they build/create things from scratch
- **operatorScore** — How much they maintain/optimize existing systems
- **creatorScore** — How much they produce content, writing, art
- **founderScore** — How likely they are to start something
- **chaosScore** — How chaotic/unpredictable their approach is

### 2. Determine Cooked Level
Use this scale based on their digital footprint intensity:
- "Not Cooked" — Normal, well-adjusted professional
- "Mildly Cooked" — Slightly online, some hobby intensity
- "Cooked" — Clearly deep in a niche, significant obsession signs
- "Deep Fried" — Multiple obsessions, very online, strong opinions
- "Absolutely Cooked" — Maximum intensity, all-in on their thing

### 3. Generate Wild Guesses (5)
Fun, speculative predictions that are obviously guesses but grounded in their profile. Each needs reasoning and confidence.

### 4. Write the Final Verdict
One memorable sentence that perfectly captures this person.

Return JSON in this format:
{
  "personalityScores": {
    "builderScore": 75,
    "operatorScore": 50,
    "creatorScore": 60,
    "founderScore": 80,
    "chaosScore": 45
  },
  "cookedLevel": "Cooked",
  "wildGuesses": [
    {
      "prediction": "string — the wild guess",
      "reasoning": "string — why you think this",
      "confidence": 30
    }
  ],
  "finalVerdict": "string — one sentence"
}`;

export interface FinalSynthesisInput {
  context: ContextPack;
  facts: Fact[];
  strongSignals: StrongSignal[];
  hiddenObsessions: HiddenObsession[];
  careerPrediction: CareerPrediction;
  startupParody: StartupParody;
  roasts: Roast[];
  coworkerQuotes: CoworkerQuote[];
  provisionalVerdict: string;
  governanceViolations: any[];
  traces: AgentTrace[];
  totalLatency: number;
  allTokenUsage: TokenUsage;
}

export interface SynthesisAIOutput {
  personalityScores: InternetPersonalityScores;
  cookedLevel: string;
  wildGuesses: WildGuess[];
  finalVerdict: string;
}

export class FinalSynthesisAgent extends BaseAgent {
  constructor() {
    const config: AgentConfig = {
      type: "final_synthesis",
      name: "Final Synthesis",
      description:
        "Combines all agent outputs into the final InvestigationReport",
      systemPrompt: SYSTEM_PROMPT,
      model: "gpt-4o",
      temperature: 0.5,
    };
    super(config);
  }

  async process(
    input: FinalSynthesisInput,
  ): Promise<{ output: InvestigationReport; trace: AgentTrace }> {
    return this.safeProcess<InvestigationReport>(async () => {
      const startTime = new Date().toISOString();
      const start = performance.now();

      const userPrompt = this.buildPrompt(input);
      const { parsed, trace } =
        await this.callAIJSON<SynthesisAIOutput>(userPrompt);

      const validated = this.validateSynthesisOutput(parsed);

      const report = this.assembleReport(input, validated);
      const endTime = new Date().toISOString();
      const latency = performance.now() - start;

      const agentTrace: AgentTrace = {
        ...trace,
        agentName: this.config.name,
        input: {
          factCount: input.facts.length,
          signalCount: input.strongSignals.length,
        },
        output: { id: report.id, profileHash: report.profileHash },
        latency,
        startTime,
        endTime,
      };

      return { output: report, trace: agentTrace };
    });
  }

  private buildPrompt(input: FinalSynthesisInput): string {
    return `Assemble the final investigation report from these components.

## Profile Summary
${input.context.summary}

## Facts (${input.facts.length})
${JSON.stringify(input.facts, null, 2)}

## Strong Signals (${input.strongSignals.length})
${JSON.stringify(input.strongSignals, null, 2)}

## Hidden Obsessions (${input.hiddenObsessions.length})
${JSON.stringify(input.hiddenObsessions, null, 2)}

## Career Prediction
${JSON.stringify(input.careerPrediction, null, 2)}

## Startup Parody
${JSON.stringify(input.startupParody, null, 2)}

## Roasts (${input.roasts.length})
${JSON.stringify(input.roasts, null, 2)}

## Coworker Quotes (${input.coworkerQuotes.length})
${JSON.stringify(input.coworkerQuotes, null, 2)}

## Provisional Verdict
${input.provisionalVerdict}

## Governance Violations (${input.governanceViolations.length})
${JSON.stringify(input.governanceViolations, null, 2)}

Generate personality scores, cooked level, 5 wild guesses, and a final verdict. Base everything on the evidence.`;
  }

  private assembleReport(
    input: FinalSynthesisInput,
    synthesis: SynthesisAIOutput,
  ): InvestigationReport {
    const cookedLevel = this.normalizeCookedLevel(synthesis.cookedLevel);
    const aggressiveWildGuesses = this.ensureWildGuesses(synthesis.wildGuesses);

    const totalTokens = input.allTokenUsage.totalTokens;
    const promptTokens = input.allTokenUsage.promptTokens;
    const completionTokens = input.allTokenUsage.completionTokens;

    const metadata: ReportMetadata = {
      model: "gpt-4o",
      provider: "openai",
      latency: input.totalLatency,
      tokenUsage: { promptTokens, completionTokens, totalTokens },
      cost: calculateCost("gpt-4o", promptTokens, completionTokens),
      promptVersion: "1.0.0",
      governancePassed: input.governanceViolations.length === 0,
      safetyChecked: true,
      generatedAt: new Date().toISOString(),
    };

    return {
      id: generateId(),
      profileHash: this.hashProfile(input.context),
      digitalProfileSummary: this.buildSummary(input.facts),
      facts: input.facts,
      strongSignals: input.strongSignals,
      hiddenObsessions: input.hiddenObsessions,
      coworkerQuotes: input.coworkerQuotes,
      startupParody: input.startupParody,
      careerPrediction: input.careerPrediction,
      brutalRoast: input.roasts,
      wildGuesses: aggressiveWildGuesses,
      finalVerdict: synthesis.finalVerdict || input.provisionalVerdict,
      personalityScores: synthesis.personalityScores || {
        builderScore: 50,
        operatorScore: 50,
        creatorScore: 50,
        founderScore: 50,
        chaosScore: 50,
      },
      cookedLevel,
      metadata,
    };
  }

  private normalizeCookedLevel(level: string): CookedLevel {
    const validLevels: CookedLevel[] = [
      "Not Cooked",
      "Mildly Cooked",
      "Cooked",
      "Deep Fried",
      "Absolutely Cooked",
    ];
    const matched = validLevels.find(
      (v) => v.toLowerCase() === level.toLowerCase().trim(),
    );
    return matched || "Cooked";
  }

  private ensureWildGuesses(guesses: WildGuess[]): WildGuess[] {
    if (!Array.isArray(guesses) || guesses.length === 0) {
      return [
        {
          prediction: "Will start a newsletter that lasts 3 issues",
          reasoning: "Every developer has one",
          confidence: 60,
        },
        {
          prediction: "Has at least 3 unfinished side projects",
          reasoning: "Classic developer pattern",
          confidence: 85,
        },
        {
          prediction: "Secretly wants to be a VC",
          reasoning: "Everyone does eventually",
          confidence: 40,
        },
        {
          prediction: "Has strong opinions on tabs vs spaces",
          reasoning: "It always comes up",
          confidence: 70,
        },
        {
          prediction: "Will migrate everything to a new framework next year",
          reasoning: "The cycle continues",
          confidence: 55,
        },
      ];
    }
    return guesses.slice(0, 5);
  }

  private buildSummary(facts: Fact[]): string {
    const summaryFacts = facts
      .slice(0, 5)
      .map((f) => f.observation)
      .join("; ");
    return summaryFacts || "Profile analysis completed.";
  }

  private hashProfile(context: ContextPack): string {
    const str = JSON.stringify(context.normalized);
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash = hash & hash;
    }
    return Math.abs(hash).toString(16).padStart(8, "0");
  }

  private validateSynthesisOutput(
    output: SynthesisAIOutput,
  ): SynthesisAIOutput {
    const defaultScores: InternetPersonalityScores = {
      builderScore: 50,
      operatorScore: 50,
      creatorScore: 50,
      founderScore: 50,
      chaosScore: 50,
    };

    const scores = output.personalityScores;
    const validatedScores: InternetPersonalityScores = scores
      ? {
          builderScore: Math.min(100, Math.max(0, scores.builderScore ?? 50)),
          operatorScore: Math.min(100, Math.max(0, scores.operatorScore ?? 50)),
          creatorScore: Math.min(100, Math.max(0, scores.creatorScore ?? 50)),
          founderScore: Math.min(100, Math.max(0, scores.founderScore ?? 50)),
          chaosScore: Math.min(100, Math.max(0, scores.chaosScore ?? 50)),
        }
      : defaultScores;

    return {
      personalityScores: validatedScores,
      cookedLevel: output.cookedLevel || "Cooked",
      wildGuesses: Array.isArray(output.wildGuesses) ? output.wildGuesses : [],
      finalVerdict:
        output.finalVerdict || "An enigmatic figure in the tech landscape.",
    };
  }
}
